export const SHOW_OPTIONS = "SHOW_OPTIONS";
export const SET_TOP_OPTIONS = "SET_TOP_OPTIONS";
export const SET_BOTTOM_OPTIONS = "SET_BOTTOM_OPTIONS";

export const CHANGE_IMAGE = "CHANGE_IMAGE";
export const SAVE_IMAGE = "SAVE_IMAGE";

export const CHANGE_COLOR_TOP = "CHANGE_COLOR_TOP";
export const CHANGE_COLOR_BOTTOM = "CHANGE_COLOR_BOTTOM";

export const CHANGE_FONT_SIZE_TOP = "CHANGE_FONT_SIZE_TOP";
export const CHANGE_FONT_SIZE_BOTTOM = "CHANGE_FONT_SIZE_BOTTOM";
